#!/bin/sh
# PreToolUse hook: blocks git commit / gh pr create commands
# that contain Co-Authored-By trailers or AI attribution text.
# This forces the agent to retry without attribution.

INPUT="$(cat)"

# Only check Bash tool calls
case "$INPUT" in
    *'"tool_name"'*'"Bash"'*) ;;
    *) exit 0 ;;
esac

# Check for git commit or checkpoint helpers with attribution text.
if echo "$INPUT" | grep -qi "git commit\|checkpoint\.sh\|commit-safe\.sh"; then
    if echo "$INPUT" | grep -qi "co[- ]\?authored[- ]\?by\|generated with\|generated by\|authored by ai\|created by ai"; then
        echo '{"decision":"block","reason":"Do not add Co-Authored-By trailers to commit messages. Commits must only show the users git identity. Remove the Co-Authored-By line and retry."}'
        exit 0
    fi
fi

# Check for gh pr create with AI attribution text or Co-Authored-By
if echo "$INPUT" | grep -qi "gh pr create"; then
    if echo "$INPUT" | grep -qi "generated with\|generated by\|authored by ai\|created by ai\|co[- ]\?authored[- ]\?by"; then
        echo '{"decision":"block","reason":"Do not add AI attribution text to PR descriptions. Remove that line and retry."}'
        exit 0
    fi
fi

exit 0
